### ISSUE TITLE
Duplicate nodes in NodeGraph and Visualizer

### ISSUE THREAD

**Issue by kbret1** [event-catalog/eventcatalog#456]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

The Domain NodeGraph and Visualizer shows duplicate nodes.

![image](https://github.com/boyney123/eventcatalog/assets/121055660/ded2a480-3572-4495-92d8-365704c82da2)

![image](https://github.com/boyney123/eventcatalog/assets/121055660/a2f6759f-c3c1-40b7-bcee-5b9ea4e07e66)

### Steps to reproduce

git clone https://github.com/kbret1/EventCatalogTest.git
cd EventCatalogTest
yarn
yarn build
yarn start

### Expected behavior

Domain NodeGraph and Visualizer should not have duplicate nodes.

### Actual behavior

Duplicate nodes are included.

### Your environment

- EventCatalog Core version used: 1.1.0
- Environment name and version: Version 117.0.5938.149 (Official Build) (arm64)
- Operating system and version: MacBook 14.0 (23A344)

**Comment by jr-araujo** [comment]
I'm also facing this issue! A loose some hours trying to figure out where could be the spot of the duplication and I saw that it could be a BUG on the NodeGraph component of the eventcatalog platform.

@boyney123 any news about it?

**Comment by steve-curran** [comment]
I am also facing this issue while evaluating this tool for adaption by our company - @boyney123

**Comment by flashmatt** [comment]
We've hit the same issue.

It would appear the Domain graph is split into publishers and subscribers and in your case @kbret1 because your service does not subscribe to anything it looks like the graph is duplicating. We noticed this on our Master Data service which publishes but does not consume.

Looking at the demo: https://app.eventcatalog.dev/domains/Orders/ It seems this is the desired behaviour but I would argue that it is better to show this in one graph instead of separate. @boyney123 would you accept a pull request to inline these into one graph? Something along the lines of:

[ PaymentProcessed ] -> Subscribed by -> [ Orders Service ]-> Publishes -> [ Order Complete ]-> subscribed by ->[ Data Lake ]

We haven't done any work to see if this is possible, I just want to confirm before we look at it. 

@robert-sykes FYI

**Comment by s1mrankaur** [comment]
My service is subscribing and it is still duplicated. @kbret1 @boyney123

**Comment by boyney123** [comment]
> app.eventcatalog.dev/domains/Orders

Hey @flashmatt 

Ah yeah I see the issue, yeah feel free to make a pull request and look into this, happy to accept that if you still have the time and bandwidth, makes sense to me!

**Comment by s1mrankaur** [comment]
Any fixes in sight for this issue?

**Comment by boyney123** [comment]
I'm currently rewriting parts in V2 of EventCatalog, faster file system reads etc. Part of this I have moved to dagre for rendering nodes, I believe this may fix the issue! So hopefully I can get something deployed soon for you all to test.

**Comment by boyney123** [comment]
Thanks for raising this issue. 

EventCatalog v2 is coming out very soon, so going to close this as I believe it’s no longer an issue in the new version. 

If you still experience this issue please raise a new issue. 

Thank you!
