### ISSUE TITLE
Backstage

### ISSUE THREAD

**Issue by hvandenb** [event-catalog/eventcatalog#731]
## Feature Request
[Backstage](https://backstage.io/) is a popular developer portal. It support catalogs and markdown documention. Ideally Event Catalog is integrated with it.

Some suggested options

1. [Plugin](https://backstage.io/docs/plugins/create-a-plugin) to allow content from EC to be shown
2. Integrate the software catalog (services etc) into EV

**Comment by boyney123** [comment]
Will be exploring this in September, any suggestions are welcome. I'm new to backstage, so any thoughts would be welcome if anyone has any.

**Comment by brunocascio** [comment]
Backstage and eventcatlog have more likely the same structure, so due to both tools are code driven (one with yaml and the other one with markdown) sounds like it will generate a lof of "duplication". Maybe if eventcatalog provides an iframe or something that can be embbed within a backstage entity could be a good experience.

Backstage lacks of visualization about events and eventcatalog provides an amazing experience for event documentation but it lacks the rest of the backstage's features.

I was doing some PoC extending backstage model creating a new `kind: Event` and adding `publishEvent` and `consumeEvent` custom relationships because there's no way to visualize who produce/consume which event in Backstage but then I found this and I would to see how it goes :)

**Comment by boyney123** [comment]
Folks this is now live! https://www.eventcatalog.dev/docs/development/plugins/backstage/intro
